CREATE TABLE `trade_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`month` varchar(8),
	`partner` varchar(255),
	`no` int,
	`paymentDate` varchar(64),
	`productName` text,
	`quantity` decimal(10,2) DEFAULT '0',
	`unitPrice` decimal(12,4) DEFAULT '0',
	`currency` varchar(16),
	`unitPriceJPY` decimal(14,4) DEFAULT '0',
	`status` varchar(64),
	`procurement` varchar(64),
	`shippingFromTokyo` varchar(64),
	`totalSales` decimal(16,4) DEFAULT '0',
	`procurementTotal` decimal(16,4) DEFAULT '0',
	`refund` decimal(14,4) DEFAULT '0',
	`shippingCost` decimal(14,4) DEFAULT '0',
	`profitWithRefund` decimal(16,4) DEFAULT '0',
	`cumulativeProfit` decimal(16,4) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trade_records_id` PRIMARY KEY(`id`)
);
