/** Synthetic examples, shared by the API suite and the browser baseline. */
export const purchaseFixtures = [
  {
    id: 910001,
    title: "【テスト】携帯ゲーム機A",
    category: "ゲーム機",
    quantity: 2,
    unitPrice: "1500.25",
    managementNo: "TEST-A",
    purchaseDate: "2026-09-01",
    status: "ordered",
    inboundClass: null,
    stage: "received",
    trackingNumber: null,
  },
  {
    id: 910002,
    title: "【テスト】ワイヤレスパッドB",
    category: "周辺機器",
    quantity: 1,
    unitPrice: "2400.00",
    managementNo: "TEST-B",
    purchaseDate: "2026-09-02",
    status: "shipped",
    inboundClass: "ebay",
    stage: "received",
    trackingNumber: "TEST-TRACK-B",
  },
  {
    id: 910003,
    title: "【テスト】収納ケースC",
    category: "周辺機器",
    quantity: 3,
    unitPrice: "400.00",
    managementNo: "TEST-C",
    purchaseDate: "2026-09-03",
    status: "ordered",
    inboundClass: "direct",
    stage: "received",
    trackingNumber: null,
  },
  {
    id: 910004,
    title: "【テスト】完了済みD",
    category: "ゲーム機",
    quantity: 1,
    unitPrice: "800.00",
    managementNo: "TEST-D",
    purchaseDate: "2026-09-04",
    status: "ordered",
    inboundClass: "ebay",
    stage: "packed",
    trackingNumber: null,
  },
  {
    id: 910005,
    title: "【テスト】入庫済みE",
    category: "ゲーム機",
    quantity: 1,
    unitPrice: "500.00",
    managementNo: "TEST-E",
    purchaseDate: "2026-09-05",
    status: "purchased",
    inboundClass: "oregon",
    stage: "registered",
    trackingNumber: null,
  },
  {
    id: 910006,
    title: "【テスト】旧日付F",
    category: "ゲーム機",
    quantity: 1,
    unitPrice: "999.00",
    managementNo: "TEST-F",
    purchaseDate: "2026-06-19",
    status: "ordered",
    inboundClass: null,
    stage: "received",
    trackingNumber: null,
  },
  {
    id: 910007,
    title: "【テスト】境界日G",
    category: "その他",
    quantity: 1,
    unitPrice: "100.00",
    managementNo: "TEST-G",
    purchaseDate: "2026-06-20",
    status: "ordered",
    inboundClass: "domestic",
    stage: "registered",
    trackingNumber: null,
  },
];
