// @ts-ignore - generated by the build script before Vercel bundles API functions.
import { createApiApp } from "../dist/api-app.js";

const appPromise = createApiApp();

export default async function handler(req: any, res: any) {
  const app = await appPromise;
  return app(req, res);
}
